### ISSUE TITLE
Supplymentary?

### ISSUE THREAD

**Issue by YangJae96** [SikaStar/IDM#12]
Hi, Thank you for great work.

I am interestined in your work and I am trying to find the supplymentary file.
Where can I find the supplementary file?

**Comment by SikaStar** [comment]
> Hi, Thank you for great work.
> 
> I am interestined in your work and I am trying to find the supplymentary file. Where can I find the supplementary file?

Hi, the supplementary file can be found at [here](https://openaccess.thecvf.com/content/ICCV2021/supplemental/Dai_IDM_An_Intermediate_ICCV_2021_supplemental.pdf)

**Comment by YangJae96** [comment]
@SikaStar 

Thanks!
