### ISSUE TITLE
About source centroids

### ISSUE THREAD

**Issue by YangJae96** [SikaStar/IDM#13]
Hi, 

![image](https://user-images.githubusercontent.com/57695621/165108988-de4495ec-d457-4ec7-ab51-319ea11652a0.png)
In the code above and also for target domain centroids,
why do you initialize source center features into the model  fully-connected layer?

Is this some kind of techique not metioned in the paper?

**Comment by SikaStar** [comment]
> Hi,
> 
> ![image](https://user-images.githubusercontent.com/57695621/165108988-de4495ec-d457-4ec7-ab51-319ea11652a0.png) In the code above and also for target domain centroids, why do you initialize source center features into the model fully-connected layer?
> 
> Is this some kind of techique not metioned in the paper?

Hi, we use this technique for the source domain to keep consistent with that in the target domain. This is not a necessary technique. You can also initialize it randomly and it may not hurt the last performance.

**Comment by YangJae96** [comment]
Oh, Thank you.
 
Target domain does initialize -> so you did same for the source domain for consistency.
Is initializing target domain centers a necessary technique?

**Comment by SikaStar** [comment]
> Oh, Thank you.
> 
> Target domain does initialize -> so you did same for the source domain for consistency. Is initializing target domain centers a necessary technique?

Initializing target domain centers can get more stable performance and make faster model convergence.

**Comment by YangJae96** [comment]
Thank you!!!
