### ISSUE TITLE
About multi-GPU

### ISSUE THREAD

**Issue by YangJae96** [SikaStar/IDM#14]
Hi, 

I can see you have used 4 GPU in the training which gives great result.

Is there a technical reason for using 4gpu like stable training that was done in 
MoCO network.  Or is it just because of the memory issue due to big batch size?

**Comment by SikaStar** [comment]
> Hi,
> 
> I can see you have used 4 GPU in the training which gives great result.
> 
> Is there a technical reason for using 4gpu like stable training that was done in MoCO network. Or is it just because of the memory issue due to big batch size?

Hi, we are sorry that we have not found the technical reason for using 4 gpus during training. Because our code is based on https://github.com/yxgeee/SpCL, the gpu number is also following SpCL.

**Comment by YangJae96** [comment]
I see Thanks!!
