### ISSUE TITLE
引用问题

### ISSUE THREAD

**Issue by shylie728** [SikaStar/IDM#17]
您好，我想请问一下，我想把您这个IDM模块加入到我的代码中，应该怎么添加？

**Comment by SikaStar** [comment]
> 您好，我想请问一下，我想把您这个IDM模块加入到我的代码中，应该怎么添加？

你好，你直接把 idm/models/idm_module.py 拷贝到你的models目录下，然后在你的 model.py 文件中引用就行了 `from .idm_module import IDM`
