### ISSUE TITLE
IDM++

### ISSUE THREAD

**Issue by shylie728** [SikaStar/IDM#18]
您好，我想问一下IDM++的代码公开了吗？

**Comment by SikaStar** [comment]
> 您好，我想问一下IDM++的代码公开了吗？

你好，因为最近有其它项目还没有时间去整理代码发布，我们会尽快更新代码上传。实现细节在论文https://arxiv.org/abs/2203.01682 里面都有讲，你可以先尝试复现一下。

**Comment by aboriginalZero** [comment]
您好，请问 IDM++ 代码什么时候会公布？

**Comment by JackeyWang777** [comment]
请问 IDM++ 代码什么时候会公布？

**Comment by dodobe** [comment]
@SikaStar 您好，请问何时可以更新 IDM++ 的代码？
