### ISSUE TITLE
Questions about running the source code

### ISSUE THREAD

**Issue by Estella218** [SikaStar/IDM#19]
Hello, author. In the process of self-training published source code, I used the configuration of one GPU and got a result about 10% different from the paper. Do you need 4 GPUs to achieve the latest effect? Is there another way to get out?

**Comment by SikaStar** [comment]
> 

Hi, in the self-training procedure, 4 gpus are the better choice than 1 gpu. We use 4 gpus for all self-training experiments. If you want to use fewer gpus, you can set a smaller batch_size to ensure 16 batch_size per gpu.

**Comment by SikaStar** [comment]
> Hello, author. In the process of self-training published source code, I used the configuration of one GPU and got a result about 10% different from the paper. Do you need 4 GPUs to achieve the latest effect? Is there another way to get out?

Hi, in the self-training procedure, 4 gpus are the better choice than 1 gpu. We use 4 gpus for all self-training experiments. If you want to use fewer gpus, you can set a smaller batch_size to ensure 16 batch_size per gpu.
