### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by shylie728** [SikaStar/IDM#20]
你好，我跑IDM的时候，出现了下图的情况，之前没太注意，但是对结果没什么影响，请问这个是正常的吗？
![image](https://user-images.githubusercontent.com/101248412/180352794-5f60145d-a5fd-4190-ae6c-ff91b27787e4.png)

**Comment by SikaStar** [comment]
> 你好，我跑IDM的时候，出现了下图的情况，之前没太注意，但是对结果没什么影响，请问这个是正常的吗？ ![image](https://user-images.githubusercontent.com/101248412/180352794-5f60145d-a5fd-4190-ae6c-ff91b27787e4.png)

你好，只要不报错就行。
