### ISSUE TITLE
代码不清晰

### ISSUE THREAD

**Issue by shylie728** [SikaStar/IDM#21]
您好，我最近在仔细的研究IDM的代码，然后有一个点我不清楚。
        bs = x.size(0)
        assert (bs%2==0)
        split = torch.split(x, int(bs/2), 0)
        x_s = split[0].contiguous() # [B, C, H, W]     [16,64,64,32]
        x_t = split[1].contiguous()
这里将输入的x进行分割，请问这是将输入进行分割，一半作为源域数据，一半作为目标域数据，还是别的意思，这里我不太理解，希望可以得到您的解答，谢谢！

**Comment by SikaStar** [comment]
> 您好，我最近在仔细的研究IDM的代码，然后有一个点我不清楚。 bs = x.size(0) assert (bs%2==0) split = torch.split(x, int(bs/2), 0) x_s = split[0].contiguous() # [B, C, H, W] [16,64,64,32] x_t = split[1].contiguous() 这里将输入的x进行分割，请问这是将输入进行分割，一半作为源域数据，一半作为目标域数据，还是别的意思，这里我不太理解，希望可以得到您的解答，谢谢！

你好，就是你理解的这个意思。这里在训练过程中，将输入数据一切为二，一半是源数据一半是目标域数据。

**Comment by shylie728** [comment]
好的，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SikaStar/IDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SikaStar/IDM] 代码不清晰 (Issue #21)





  
您好，我最近在仔细的研究IDM的代码，然后有一个点我不清楚。 bs = x.size(0) assert (bs%2==0) split = torch.split(x, int(bs/2), 0) x_s = split[0].contiguous() # [B, C, H, W] [16,64,64,32] x_t = split[1].contiguous() 这里将输入的x进行分割，请问这是将输入进行分割，一半作为源域数据，一半作为目标域数据，还是别的意思，这里我不太理解，希望可以得到您的解答，谢谢！
  
你好，就是你理解的这个意思。这里在训练过程中，将输入数据一切为二，一半是源数据一半是目标域数据。
