### ISSUE TITLE
推理阶段的疑问

### ISSUE THREAD

**Issue by lanyufei** [SikaStar/IDM#22]
你好，请问一下在模型推理阶段是没有用到IDM模块吗？

**Comment by SikaStar** [comment]
> 你好，请问一下在模型推理阶段是没有用到IDM模块吗？

你好，是的。我们的IDM模块只用在网络训练阶段，在推理阶段该模块是被丢弃的。

**Comment by lanyufei** [comment]
明白了，感谢你的回答
