### ISSUE TITLE
issue about reproduced results

### ISSUE THREAD

**Issue by zaiquanyang** [SikaStar/IDM#3]
When I use the given example as follow
```
# IBN-ResNet-50 + IDM
CUDA_VISIBLE_DEVICES=0,1,2,3 \
sh scripts/run_idm_xbm.sh market1501 dukemtmc resnet_ibn50a_idm 0 0.7 0.1 1.0
```
, I can not reproduce the reported mAP by a margin of 9 \% .  
Looking forward to your reply.

**Comment by SikaStar** [comment]
> When I use the given example as follow
> 
> ```
> # IBN-ResNet-50 + IDM
> CUDA_VISIBLE_DEVICES=0,1,2,3 \
> sh scripts/run_idm_xbm.sh market1501 dukemtmc resnet_ibn50a_idm 0 0.7 0.1 1.0
> ```
> 
> , I can not reproduce the reported mAP by a margin of 9 % .
> Looking forward to your reply.

Hi, do you mean that you got mAP=62.1%? If so, maybe you have not downloaded the Imagenet-pretrained model from this [link](https://drive.google.com/drive/folders/1thS2B8UOSBi_cJX6zRy6YYRwz_nVFI_S) and save it under the path of `logs/pretrained/`

**Comment by zaiquanyang** [comment]
> > When I use the given example as follow
> > ```
> > # IBN-ResNet-50 + IDM
> > CUDA_VISIBLE_DEVICES=0,1,2,3 \
> > sh scripts/run_idm_xbm.sh market1501 dukemtmc resnet_ibn50a_idm 0 0.7 0.1 1.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > , I can not reproduce the reported mAP by a margin of 9 % .
> > Looking forward to your reply.
> 
> Hi, do you mean that you got mAP=62.1%? If so, maybe you have not downloaded the Imagenet-pretrained model from this [link](https://drive.google.com/drive/folders/1thS2B8UOSBi_cJX6zRy6YYRwz_nVFI_S) and save it under the path of `logs/pretrained/`

I indeed followed your instructions to download the network and put it in the specified location (in my machine) as follow:
```
/data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
```
 and I train the model about 40 epochs.

**Comment by SikaStar** [comment]
> ```
> /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> ```

What are the results you have got?

**Comment by zaiquanyang** [comment]
> > ```
> > /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> > ```
> 
> What are the results you have got?

Mean AP: 55.5%
CMC Scores:
  top-1          74.7%
  top-5          84.5%
  top-10         87.1%

 * Finished epoch  44  model mAP: 55.5%  best: 61.0%

**Comment by SikaStar** [comment]
> > > ```
> > > /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> > > ```
> > 
> > 
> > What are the results you have got?
> 
> Mean AP: 55.5%
> CMC Scores:
> top-1 74.7%
> top-5 84.5%
> top-10 87.1%
> 
> * Finished epoch  44  model mAP: 55.5%  best: 61.0%

It is strange! Have you trained with 4 GPUs?

**Comment by zaiquanyang** [comment]
> > > > ```
> > > > /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> > > > ```
> > > 
> > > 
> > > What are the results you have got?
> > 
> > 
> > Mean AP: 55.5%
> > CMC Scores:
> > top-1 74.7%
> > top-5 84.5%
> > top-10 87.1%
> > 
> > * Finished epoch  44  model mAP: 55.5%  best: 61.0%
> 
> It is strange! Have you trained with 4 GPUs?

I just run it on a v100GPU

**Comment by SikaStar** [comment]
> > > > > ```
> > > > > /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> > > > > ```
> > > > 
> > > > 
> > > > What are the results you have got?
> > > 
> > > 
> > > Mean AP: 55.5%
> > > CMC Scores:
> > > top-1 74.7%
> > > top-5 84.5%
> > > top-10 87.1%
> > > 
> > > * Finished epoch  44  model mAP: 55.5%  best: 61.0%
> > 
> > 
> > It is strange! Have you trained with 4 GPUs?
> 
> I just run it on a v100GPU

Hi, I have not conducted these experiments on a single GPU. All my experiments are trained on 4 GPUs.  As far as I know, the number of GPUs can affect the results significantly. You can try it on 4 GPUs and you will get similar results that I reported in my paper.

**Comment by zaiquanyang** [comment]
> > > > > > ```
> > > > > > /data/code/DA_ReID/IDM/logs/pretrained/resnet50_ibn_a.pth.tar
> > > > > > ```
> > > > > 
> > > > > 
> > > > > What are the results you have got?
> > > > 
> > > > 
> > > > Mean AP: 55.5%
> > > > CMC Scores:
> > > > top-1 74.7%
> > > > top-5 84.5%
> > > > top-10 87.1%
> > > > 
> > > > * Finished epoch  44  model mAP: 55.5%  best: 61.0%
> > > 
> > > 
> > > It is strange! Have you trained with 4 GPUs?
> > 
> > 
> > I just run it on a v100GPU
> 
> Hi, I have not conducted these experiments on a single GPU. All my experiments are trained on 4 GPUs. As far as I know, the number of GPUs can affect the results significantly. You can try it on 4 GPUs and you will get similar results that I reported in my paper.

ok, thanks very much for your reply!
