### ISSUE TITLE
Hi, thanks very much for sharing this wonderful work. There are some questions about this work.

### ISSUE THREAD

**Issue by ddghjikle** [SikaStar/IDM#4]
Congratulations on obtaining the ICCV Oral and thank you very much for sharing corresponding codes. 

After reading these codes, i wish the following question can be addressed: in the train_baseline.py, line 166, I am wondering why parameters of the classifier are defined rather than learned. 

On the other hand, in each epoch, samples in the unlabeled target domain are clustered to generate pseudo labels. Is it possible not to generate pseudo labels by using metric learning or subspace learning methods?

**Comment by SikaStar** [comment]
> Congratulations on obtaining the ICCV Oral and thank you very much for sharing corresponding codes.
> 
> After reading these codes, i wish the following question can be addressed: in the train_baseline.py, line 166, I am wondering why parameters of the classifier are defined rather than learned.
> 
> On the other hand, in each epoch, samples in the unlabeled target domain are clustered to generate pseudo labels. Is it possible not to generate pseudo labels by using metric learning or subspace learning methods?

Hi, 
(1) For your first question: The code in [Line 166](https://github.com/SikaStar/IDM/blob/1789aeb1ab8dcb2bc5712e0683257dae9a51338e/examples/train_baseline.py#L166) is not necessary. It is just used for parameters' initialization. You can change it to other initialization methods.

(2) For your second question: Triple loss and classification loss with pseudo labels could be seen as a kind of metric learning loss. If not generating pseudo labels like ours, you could try to use contrastive loss like this paper [link](https://openaccess.thecvf.com/content_CVPR_2019/html/Zhong_Invariance_Matters_Exemplar_Memory_for_Domain_Adaptive_Person_Re-Identification_CVPR_2019_paper.html). Other methods like subspace learning are also interesting in solving the problem of UDA ReID.
