### ISSUE TITLE
Hi, during running the released codes, an error happens.

### ISSUE THREAD

**Issue by ddghjikle** [SikaStar/IDM#5]
During running the run_strong_baseline.sh, an error happens in the idm/evaluation_metrics/rank.py, line 108. The specific error information is as follows (For efficiently debugging, i directly run the evaluator.evaluate() function before training. Of course, this error happens during running the original codes): 
Traceback (most recent call last):
  File "examples/train_baseline.py", line 329, in <module>
    main()
  File "examples/train_baseline.py", line 117, in main
    main_worker(args)
  File "examples/train_baseline.py", line 143, in main_worker
    _, mAP = evaluator.evaluate(test_loader_target, dataset_target.query, dataset_target.gallery, cmc_flag=True)
  File "./idm/evaluators.py", line 140, in evaluate
    results = evaluate_all(query_features, gallery_features, distmat, query=query, gallery=gallery, cmc_flag=cmc_flag)
  File "./idm/evaluators.py", line 118, in evaluate_all
    max_rank=50, use_metric_cuhk03=False, use_cython=True)
  File "./idm/evaluation_metrics/rank.py", line 209, in evaluate_rank
    use_metric_cuhk03
  File "./idm/evaluation_metrics/rank.py", line 169, in evaluate_py
    distmat, q_pids, g_pids, q_camids, g_camids, max_rank
  File "./idm/evaluation_metrics/rank.py", line 112, in eval_market1501
    matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)
TypeError: only integer tensors of a single element can be converted to an index
 Could you please give me some comments about this error?

**Comment by ddghjikle** [comment]
This error is caused by running g_pids[indices]. It is easy to find that the 'indices' is a 2D tensor.

**Comment by SikaStar** [comment]
> This error is caused by running g_pids[indices]. It is easy to find that the 'indices' is a 2D tensor.

Have you run the command as follows: `cd IDM/idm/evaluation_metrics/rank_cylib && make all`.

**Comment by ddghjikle** [comment]
Thank you very much for the comments








&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SikaStar/IDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SikaStar/IDM] Hi, during running the released codes, an error happens. (#5)





  
This error is caused by running g_pids[indices]. It is easy to find that the 'indices' is a 2D tensor.
  
Have you run the command as follows: cd IDM/idm/evaluation_metrics/rank_cylib &amp;&amp; make all.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
