### ISSUE TITLE
TypeError: only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by xkxkx** [SikaStar/IDM#6]
epoh 0 结束后出现如下错误，请问这会是什么原因呢
`Traceback (most recent call last):
  File "examples/train_idm.py", line 330, in <module>
    main()
  File "examples/train_idm.py", line 122, in main
    main_worker(args)
  File "examples/train_idm.py", line 235, in main_worker
    _, mAP = evaluator.evaluate(test_loader_target, dataset_target.query, dataset_target.gallery, cmc_flag=True)
  File "./idm/evaluators.py", line 140, in evaluate
    results = evaluate_all(query_features, gallery_features, distmat, query=query, gallery=gallery, cmc_flag=cmc_flag)
  File "./idm/evaluators.py", line 118, in evaluate_all
    max_rank=50, use_metric_cuhk03=False, use_cython=True)
  File "./idm/evaluation_metrics/rank.py", line 205, in evaluate_rank
    use_metric_cuhk03
  File "./idm/evaluation_metrics/rank.py", line 165, in evaluate_py
    distmat, q_pids, g_pids, q_camids, g_camids, max_rank
  File "./idm/evaluation_metrics/rank.py", line 108, in eval_market1501
    matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)
TypeError: only integer tensors of a single element can be converted to an index
`

**Comment by SikaStar** [comment]
> epoh 0 结束后出现如下错误，请问这会是什么原因呢
> `Traceback (most recent call last): File "examples/train_idm.py", line 330, in <module> main() File "examples/train_idm.py", line 122, in main main_worker(args) File "examples/train_idm.py", line 235, in main_worker _, mAP = evaluator.evaluate(test_loader_target, dataset_target.query, dataset_target.gallery, cmc_flag=True) File "./idm/evaluators.py", line 140, in evaluate results = evaluate_all(query_features, gallery_features, distmat, query=query, gallery=gallery, cmc_flag=cmc_flag) File "./idm/evaluators.py", line 118, in evaluate_all max_rank=50, use_metric_cuhk03=False, use_cython=True) File "./idm/evaluation_metrics/rank.py", line 205, in evaluate_rank use_metric_cuhk03 File "./idm/evaluation_metrics/rank.py", line 165, in evaluate_py distmat, q_pids, g_pids, q_camids, g_camids, max_rank File "./idm/evaluation_metrics/rank.py", line 108, in eval_market1501 matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32) TypeError: only integer tensors of a single element can be converted to an index `

你好，你是否没对c代码那部分进行编译？按照说明里面的执行这一步看看`cd IDM/idm/evaluation_metrics/rank_cylib && make all`

**Comment by xkxkx** [comment]
@SikaStar 谢谢你！
