### ISSUE TITLE
Hi, could you please release the MSMT17_v1 dataset?

### ISSUE THREAD

**Issue by ddghjikle** [SikaStar/IDM#7]
Hi, i have re-produced most results by running the released codes. However, for tasks related to the MSMT17 dataset, all of them are failed because the four txt files and images are not released. Though i have tried to implement versions of the MSMT17 dataset from other websites, but the codes cannot work. Therefore, could you please share us with the MSMT17_v1 dataset used in your experiments?

**Comment by SikaStar** [comment]
> Hi, i have re-produced most results by running the released codes. However, for tasks related to the MSMT17 dataset, all of them are failed because the four txt files and images are not released. Though i have tried to implement versions of the MSMT17 dataset from other websites, but the codes cannot work. Therefore, could you please share us with the MSMT17_v1 dataset used in your experiments?

Hi, because of the copyright of this dataset, please contact the authors (Prof. Shiliang Zhang, e-mail: slzhang.jdl@pku.edu.cn) of MSMT17 to get the download link.
