### ISSUE TITLE
关于resnet50_ibn训练示例的错误

### ISSUE THREAD

**Issue by Luxios22** [SikaStar/IDM#8]
您好，我按您的readme进行测试时，跑到
CUDA_VISIBLE_DEVICES=0,1,2,3 sh scripts/run_strong_baseline.sh market1501 dukemtmc resnet_ibn50a
这句后，出现了以下错误

> ==> Create pseudo labels for unlabeled target domain with DBSCAN clustering
Computing original distance...
Computing Jaccard distance...
Time cost: 238.44885563850403Clustering and labeling... 
Clustered into 538 
Traceback (most recent call last):  
File "examples/train_baseline.py", line 321, in <module>    
main()  
File "examples/train_baseline.py", line 117, in main    
main_worker(args)  
File "examples/train_baseline.py", line 224, in main_worker    
print_freq=args.print_freq, train_iters=args.iters, use_xbm=args.use_xbm)  
File "./idm/trainers.py", line 62, in train    
prob, feats = self._forward(inputs)
ValueError: too many values to unpack (expected 2)

然后我查看了models/resnet_ibn.py，发现这个文件的forward函数仅返回x或prob或bn_x，即每次只返回一个值，与idm/trainers.py中出错的这句相矛盾。

不知道这个出错确实是这个部分有代码错误，还是说有可能有别的原因呢？

**Comment by SikaStar** [comment]
> 您好，我按您的readme进行测试时，跑到 CUDA_VISIBLE_DEVICES=0,1,2,3 sh scripts/run_strong_baseline.sh market1501 dukemtmc resnet_ibn50a 这句后，出现了以下错误
> 
> > ==> Create pseudo labels for unlabeled target domain with DBSCAN clustering
> > Computing original distance...
> > Computing Jaccard distance...
> > Time cost: 238.44885563850403Clustering and labeling...
> > Clustered into 538
> > Traceback (most recent call last):
> > File "examples/train_baseline.py", line 321, in 
> > main()
> > File "examples/train_baseline.py", line 117, in main
> > main_worker(args)
> > File "examples/train_baseline.py", line 224, in main_worker
> > print_freq=args.print_freq, train_iters=args.iters, use_xbm=args.use_xbm)
> > File "./idm/trainers.py", line 62, in train
> > prob, feats = self._forward(inputs)
> > ValueError: too many values to unpack (expected 2)
> 
> 然后我查看了models/resnet_ibn.py，发现这个文件的forward函数仅返回x或prob或bn_x，即每次只返回一个值，与idm/trainers.py中出错的这句相矛盾。
> 
> 不知道这个出错确实是这个部分有代码错误，还是说有可能有别的原因呢？

您好，是我代码的问题，感谢您指出来，我已经修改了该bug，https://github.com/SikaStar/IDM/blob/a7bff044cf3d4e46876cfbfa0936580f32a88fc4/idm/models/resnet_ibn.py#L96

**Comment by Luxios22** [comment]
感谢您的快速答复与修复！
