### ISSUE TITLE
Question about TripletLoss code

### ISSUE THREAD

**Issue by SuperbTUM** [SikaStar/IDM#9]
Hi. In the code of Triplet loss (naive version, not xbm version), I found out that the distance matrix was defined as L2 distance between two identical matrices: emb and emb, 
`mat_dist = euclidean_dist(emb, emb)` 
which will make no contribution to finding the hardest positive and negative samples. Not sure what it means.

**Comment by SikaStar** [comment]
> Hi. In the code of Triplet loss (naive version, not xbm version), I found out that the distance matrix was defined as L2 distance between two identical matrices: emb and emb, `mat_dist = euclidean_dist(emb, emb)` which will make no contribution to finding the hardest positive and negative samples. Not sure what it means.

Hi, we use the `_batch_hard()` function to mine the hardest positive and negatives. Please refer to https://github.com/SikaStar/IDM/blob/a7bff044cf3d4e46876cfbfa0936580f32a88fc4/idm/loss/triplet.py#L49

**Comment by SuperbTUM** [comment]
Thanks for the quick response. I indeed noticed the `_batch_hard` function. Just want to check that `mat_dist` here is a zero matrix, right?

**Comment by SikaStar** [comment]
> Thanks for the quick response. I indeed noticed the `_batch_hard` function. Just want to check that `mat_dist` here is a zero matrix, right?

No, `mat_dist` is the pair-wise distance matrix and only the diagonal elements are zeros, you can debug the code to check it.

**Comment by SuperbTUM** [comment]
I see. Thanks a lot!
